export const challenges = [
  {
    id: "py-hello",
    slug: "py-hello",
    title: "Hello, learner",
    skillId: "python-setup",
    language: "python",
    difficulty: "beginner",
    estimatedMinutes: 5,
    prompt: "Write a function `greet(name)` that returns the string `Hello, {name}!`.",
    starter: "def greet(name):\n    ...\n",
    tests: [
      {
        id: "t1",
        description: "greet('Ada') -> 'Hello, Ada!'",
        code: "assert greet('Ada') == 'Hello, Ada!'",
      },
      {
        id: "t2",
        description: "greet('LearnPath') includes the name",
        code: "assert 'LearnPath' in greet('LearnPath')",
      },
    ],
    hints: ["Return a string. Do not print.", "Use an f-string or + concatenation."],
  },
  {
    id: "py-fizzbuzz",
    slug: "py-fizzbuzz",
    title: "FizzBuzz",
    skillId: "python-syntax",
    language: "python",
    difficulty: "beginner",
    estimatedMinutes: 15,
    prompt:
      "Write `fizzbuzz(n)` that returns a list of strings for 1..n. Multiples of 3 become 'Fizz', of 5 'Buzz', of both 'FizzBuzz', otherwise the number as a string.",
    starter: "def fizzbuzz(n):\n    result = []\n    # your code\n    return result\n",
    tests: [
      {
        id: "t1",
        description: "first 5 values",
        code: "assert fizzbuzz(5) == ['1', '2', 'Fizz', '4', 'Buzz']",
      },
      {
        id: "t2",
        description: "15 is FizzBuzz",
        code: "assert fizzbuzz(15)[-1] == 'FizzBuzz'",
      },
    ],
    hints: ["Check 15 before 3 or 5.", "Convert numbers with str()."],
  },
  {
    id: "py-palindrome",
    slug: "py-palindrome",
    title: "Palindrome",
    skillId: "python-functions",
    language: "python",
    difficulty: "beginner",
    estimatedMinutes: 10,
    prompt: "Write `is_palindrome(text)` that ignores case and non-alphanumeric characters.",
    starter: "def is_palindrome(text):\n    ...\n",
    tests: [
      {
        id: "t1",
        description: "simple",
        code: "assert is_palindrome('RaceCar') is True",
      },
      {
        id: "t2",
        description: "punctuation",
        code: "assert is_palindrome('A man, a plan, a canal: Panama') is True",
      },
      {
        id: "t3",
        description: "negative",
        code: "assert is_palindrome('LearnPath') is False",
      },
    ],
    hints: ["Normalize with .lower() and keep only c.isalnum()."],
  },
  {
    id: "py-wordcount",
    slug: "py-wordcount",
    title: "Word count",
    skillId: "python-data-structures",
    language: "python",
    difficulty: "beginner",
    estimatedMinutes: 15,
    prompt: "Write `word_count(text)` returning a dict of lowercase word -> count. Words are alphanumeric runs.",
    starter: "def word_count(text):\n    ...\n",
    tests: [
      {
        id: "t1",
        description: "basic counts",
        code: "assert word_count('To be or not to be') == {'to': 2, 'be': 2, 'or': 1, 'not': 1}",
      },
    ],
    hints: ["Split on whitespace, strip punctuation, lowercase."],
  },
  {
    id: "py-counter-class",
    slug: "py-counter-class",
    title: "Counter class",
    skillId: "python-oop",
    language: "python",
    difficulty: "beginner",
    estimatedMinutes: 15,
    prompt: "Implement class `Counter` with increment(), decrement(), and a value property starting at 0. decrement() must not go below 0.",
    starter: "class Counter:\n    def __init__(self):\n        ...\n",
    tests: [
      {
        id: "t1",
        description: "increment",
        code: "c = Counter()\nc.increment()\nc.increment()\nassert c.value == 2",
      },
      {
        id: "t2",
        description: "floor at 0",
        code: "c = Counter()\nc.decrement()\nassert c.value == 0",
      },
    ],
    hints: ["Store self._value. Expose it via @property or a .value attribute."],
  },
  {
    id: "py-safe-divide",
    slug: "py-safe-divide",
    title: "Safe divide",
    skillId: "python-errors",
    language: "python",
    difficulty: "beginner",
    estimatedMinutes: 10,
    prompt: "Write `safe_divide(a, b)` that returns a/b, or None if b is 0.",
    starter: "def safe_divide(a, b):\n    ...\n",
    tests: [
      { id: "t1", description: "normal", code: "assert safe_divide(10, 2) == 5" },
      { id: "t2", description: "zero", code: "assert safe_divide(1, 0) is None" },
    ],
    hints: ["Guard before dividing, or catch ZeroDivisionError."],
  },
  {
    id: "js-fizzbuzz",
    slug: "js-fizzbuzz",
    title: "FizzBuzz (JS)",
    skillId: "javascript-fundamentals",
    language: "javascript",
    difficulty: "beginner",
    estimatedMinutes: 15,
    prompt: "Export function `fizzbuzz(n)` returning an array of strings for 1..n with Fizz/Buzz/FizzBuzz rules.",
    starter: "export function fizzbuzz(n) {\n  const out = [];\n  return out;\n}\n",
    tests: [
      {
        id: "t1",
        description: "n=5",
        code: "assertEqual(fizzbuzz(5), ['1','2','Fizz','4','Buzz'])",
      },
    ],
    hints: ["Use n % 15 === 0 first."],
  },
  {
    id: "js-unique",
    slug: "js-unique",
    title: "Unique values",
    skillId: "javascript-fundamentals",
    language: "javascript",
    difficulty: "beginner",
    estimatedMinutes: 10,
    prompt: "Export `unique(arr)` that returns a new array with duplicates removed, preserving first-seen order.",
    starter: "export function unique(arr) {\n  return arr;\n}\n",
    tests: [
      {
        id: "t1",
        description: "order preserved",
        code: "assertEqual(unique([1, 2, 1, 3, 2]), [1, 2, 3])",
      },
    ],
    hints: ["A Set preserves insertion order in JS."],
  },
  {
    id: "ts-narrow",
    slug: "ts-narrow",
    title: "Narrow a union",
    skillId: "typescript-fundamentals",
    language: "typescript",
    difficulty: "beginner",
    estimatedMinutes: 15,
    prompt:
      "Export `area(shape: {kind:'circle', r:number} | {kind:'rect', w:number, h:number}): number`. Circles use Math.PI * r * r.",
    starter:
      "type Shape = { kind: 'circle'; r: number } | { kind: 'rect'; w: number; h: number };\n\nexport function area(shape: Shape): number {\n  return 0;\n}\n",
    tests: [
      {
        id: "t1",
        description: "rect",
        code: "assertEqual(area({kind:'rect', w:3, h:4}), 12)",
      },
      {
        id: "t2",
        description: "circle",
        code: "if (Math.abs(area({kind:'circle', r:1}) - Math.PI) > 1e-6) throw new Error('circle area')",
      },
    ],
    hints: ["Switch on shape.kind. TypeScript will narrow."],
  },
  {
    id: "sql-books",
    slug: "sql-books",
    title: "Books by author",
    skillId: "sql-fundamentals",
    language: "sql",
    difficulty: "beginner",
    estimatedMinutes: 15,
    prompt:
      "Return title and author name for books published in 2020 or later, alphabetically by title. Columns must be named title, author.",
    starter: "SELECT title FROM books;\n",
    tests: [
      {
        id: "t1",
        description: "columns and filter",
        code: "expectColumns:title,author",
      },
    ],
    hints: ["JOIN authors ON books.author_id = authors.id", "WHERE year >= 2020", "ORDER BY title"],
  },
  {
    id: "html-profile",
    slug: "html-profile",
    title: "Accessible profile card",
    skillId: "html-css",
    language: "html",
    difficulty: "beginner",
    estimatedMinutes: 20,
    prompt:
      "Build a profile card with a heading (h1) 'Ada Lovelace', a paragraph, and a link to https://en.wikipedia.org/wiki/Ada_Lovelace whose accessible name includes 'Wikipedia'.",
    starter: "<article>\n  <!-- your markup -->\n</article>\n<style>\n  article { font-family: sans-serif; }\n</style>\n",
    tests: [
      { id: "t1", description: "h1 present", code: "assertDocument:h1" },
      { id: "t2", description: "wikipedia link", code: "assertDocument:a[href*='wikipedia']" },
    ],
    hints: ["Use semantic tags. Style is optional."],
  },
];
