const V = "2026-09-01";

export const resources = [
  {
    id: "fcc-python",
    title: "Python for Everybody — full course",
    provider: "freeCodeCamp / Dr. Chuck",
    url: "https://www.youtube.com/watch?v=8DvywoWv6fI",
    youtubeId: "8DvywoWv6fI",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 840,
    language: "en",
    topics: ["python"],
    projectBased: true,
    editorScore: 94,
    lastVerified: V,
    review: { clarity: 5, handsOn: 4, freshness: 3, projects: 4, beginner: 5 },
    status: "active",
    editorNote:
      "University-paced Python with exercises. Pause often and type every example. LearnPath editorial score reflects clarity, cost (free), and project density — not an objective ranking.",
    labels: ["best-beginner", "best-overall"],
  },
  {
    id: "fcc-python-4h",
    title: "Python — 4.5 hour beginner course",
    provider: "freeCodeCamp",
    url: "https://www.youtube.com/watch?v=rfscVS0vtbw",
    youtubeId: "rfscVS0vtbw",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 270,
    language: "en",
    topics: ["python"],
    projectBased: false,
    editorScore: 88,
    lastVerified: V,
    status: "active",
    editorNote: "Shorter path through syntax if you already program in another language.",
    labels: ["fastest"],
  },
  {
    id: "python-docs",
    title: "The Python Tutorial (official)",
    provider: "Python Software Foundation",
    url: "https://docs.python.org/3/tutorial/",
    type: "documentation",
    level: "beginner",
    durationMinutes: 180,
    language: "en",
    topics: ["python"],
    projectBased: false,
    editorScore: 96,
    lastVerified: V,
    review: { clarity: 4, handsOn: 2, freshness: 5, projects: 1, beginner: 3 },
    status: "active",
    editorNote: "Canonical reference. Use alongside video, not instead of typing code.",
    labels: ["official-docs"],
  },
  {
    id: "realpython-oop",
    title: "Object-Oriented Programming in Python",
    provider: "Real Python",
    url: "https://realpython.com/python3-object-oriented-programming/",
    type: "article",
    level: "intermediate",
    durationMinutes: 50,
    language: "en",
    topics: ["python", "oop"],
    projectBased: false,
    editorScore: 90,
    lastVerified: V,
    review: { clarity: 5, handsOn: 3, freshness: 4, projects: 2, beginner: 3 },
    status: "active",
    editorNote: "Clear mental model for classes without framework noise.",
    labels: ["best-overall"],
  },
  {
    id: "pytest-docs",
    title: "pytest documentation",
    provider: "pytest",
    url: "https://docs.pytest.org/en/stable/getting-started.html",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 40,
    language: "en",
    topics: ["python", "testing"],
    projectBased: false,
    editorScore: 93,
    lastVerified: V,
    review: { clarity: 4, handsOn: 3, freshness: 5, projects: 2, beginner: 2 },
    status: "active",
    editorNote: "Start with assert, fixtures later.",
    labels: ["official-docs"],
  },
  {
    id: "fcc-git",
    title: "Git and GitHub — crash course",
    provider: "freeCodeCamp / Colt Steele",
    url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
    youtubeId: "RGOj5yH7evk",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 70,
    language: "en",
    topics: ["git"],
    projectBased: true,
    editorScore: 91,
    lastVerified: V,
    review: { clarity: 4, handsOn: 3, freshness: 3, projects: 2, beginner: 5 },
    status: "active",
    editorNote: "Follow along in a real repo. Create the GitHub repo yourself.",
    labels: ["best-beginner"],
  },
  {
    id: "pro-git",
    title: "Pro Git book",
    provider: "Scott Chacon / Ben Straub",
    url: "https://git-scm.com/book/en/v2",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 360,
    language: "en",
    topics: ["git"],
    projectBased: false,
    editorScore: 95,
    lastVerified: V,
    review: { clarity: 4, handsOn: 3, freshness: 4, projects: 2, beginner: 3 },
    status: "active",
    editorNote: "Chapters 1–3 are enough for V1 learners; the rest is reference.",
    labels: ["official-docs"],
  },
  {
    id: "fcc-sql",
    title: "SQL — full course",
    provider: "freeCodeCamp / Mike Dane",
    url: "https://www.youtube.com/watch?v=HXV3zeQKqGY",
    youtubeId: "HXV3zeQKqGY",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 240,
    language: "en",
    topics: ["sql"],
    projectBased: true,
    editorScore: 90,
    lastVerified: V,
    review: { clarity: 5, handsOn: 4, freshness: 3, projects: 3, beginner: 5 },
    status: "active",
    editorNote: "Pause and run every query in the LearnPath SQL playground.",
    labels: ["best-beginner"],
  },
  {
    id: "sqlite-docs",
    title: "SQLite language documentation",
    provider: "SQLite",
    url: "https://www.sqlite.org/lang.html",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 90,
    language: "en",
    topics: ["sql"],
    projectBased: false,
    editorScore: 92,
    lastVerified: V,
    review: { clarity: 4, handsOn: 2, freshness: 4, projects: 1, beginner: 2 },
    status: "active",
    editorNote: "Dialect used by the in-browser playground.",
    labels: ["official-docs"],
  },
  {
    id: "fcc-html-css",
    title: "HTML & CSS — full course",
    provider: "freeCodeCamp",
    url: "https://www.youtube.com/watch?v=mU6anWqZJcc",
    youtubeId: "mU6anWqZJcc",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 360,
    language: "en",
    topics: ["html", "css"],
    projectBased: true,
    editorScore: 89,
    lastVerified: V,
    review: { clarity: 5, handsOn: 4, freshness: 3, projects: 4, beginner: 5 },
    status: "active",
    editorNote: "Build the layouts in the HTML playground rather than only watching.",
    labels: ["best-beginner"],
  },
  {
    id: "mdn-html",
    title: "MDN HTML elements reference",
    provider: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    type: "documentation",
    level: "beginner",
    durationMinutes: 120,
    language: "en",
    topics: ["html"],
    projectBased: false,
    editorScore: 97,
    lastVerified: V,
    review: { clarity: 5, handsOn: 4, freshness: 5, projects: 2, beginner: 5 },
    status: "active",
    editorNote: "The source of truth for HTML. Prefer MDN over random blogs.",
    labels: ["official-docs"],
  },
  {
    id: "fcc-javascript",
    title: "JavaScript — full course",
    provider: "freeCodeCamp",
    url: "https://www.youtube.com/watch?v=jS4aFq5-91M",
    youtubeId: "jS4aFq5-91M",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 480,
    language: "en",
    topics: ["javascript"],
    projectBased: true,
    editorScore: 91,
    lastVerified: V,
    review: { clarity: 5, handsOn: 4, freshness: 3, projects: 4, beginner: 5 },
    status: "active",
    editorNote: "Long but coherent. Pair with MDN and the JS playground.",
    labels: ["best-overall"],
  },
  {
    id: "javascript-info",
    title: "The Modern JavaScript Tutorial",
    provider: "javascript.info",
    url: "https://javascript.info/",
    type: "article",
    level: "beginner",
    durationMinutes: 600,
    language: "en",
    topics: ["javascript"],
    projectBased: false,
    editorScore: 95,
    lastVerified: V,
    review: { clarity: 5, handsOn: 4, freshness: 4, projects: 2, beginner: 4 },
    status: "active",
    editorNote: "Best written JS curriculum we know. Free.",
    labels: ["best-overall", "hidden-gem"],
  },
  {
    id: "mdn-js",
    title: "MDN JavaScript guide",
    provider: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    type: "documentation",
    level: "beginner",
    durationMinutes: 180,
    language: "en",
    topics: ["javascript"],
    projectBased: false,
    editorScore: 96,
    lastVerified: V,
    review: { clarity: 5, handsOn: 4, freshness: 5, projects: 2, beginner: 4 },
    status: "active",
    editorNote: "Use as the official companion to any video.",
    labels: ["official-docs"],
  },
  {
    id: "fcc-typescript",
    title: "TypeScript — full course",
    provider: "freeCodeCamp / Net Ninja",
    url: "https://www.youtube.com/watch?v=30LPxPGDQAw",
    youtubeId: "30LPxPGDQAw",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 160,
    language: "en",
    topics: ["typescript"],
    projectBased: false,
    editorScore: 86,
    lastVerified: V,
    status: "active",
    editorNote: "Enough to read and write TS in React/Node projects.",
    labels: ["best-beginner"],
  },
  {
    id: "ts-handbook",
    title: "TypeScript Handbook",
    provider: "Microsoft",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 180,
    language: "en",
    topics: ["typescript"],
    projectBased: false,
    editorScore: 97,
    lastVerified: V,
    status: "active",
    editorNote: "Start with Everyday Types and Narrowing.",
    labels: ["official-docs"],
  },
  {
    id: "fcc-react",
    title: "React — full course (hooks)",
    provider: "freeCodeCamp / Bob Ziroll",
    url: "https://www.youtube.com/watch?v=bMknfKXIFA8",
    youtubeId: "bMknfKXIFA8",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 720,
    language: "en",
    topics: ["react", "javascript"],
    projectBased: true,
    editorScore: 90,
    lastVerified: V,
    status: "active",
    editorNote: "Project-heavy. Skip class components if the recording still shows them.",
    labels: ["project-based", "best-beginner"],
  },
  {
    id: "react-docs",
    title: "React docs — Learn React",
    provider: "Meta",
    url: "https://react.dev/learn",
    type: "documentation",
    level: "beginner",
    durationMinutes: 180,
    language: "en",
    topics: ["react"],
    projectBased: true,
    editorScore: 98,
    lastVerified: V,
    status: "active",
    editorNote: "The interactive official tutorial is better than most paid courses.",
    labels: ["official-docs", "best-overall"],
  },
  {
    id: "fcc-node",
    title: "Node.js and Express — full course",
    provider: "freeCodeCamp / John Smilga",
    url: "https://www.youtube.com/watch?v=Oe421EPjeBE",
    youtubeId: "Oe421EPjeBE",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 480,
    language: "en",
    topics: ["node", "express"],
    projectBased: true,
    editorScore: 88,
    lastVerified: V,
    status: "active",
    editorNote: "Build the API; do not copy-paste entire files.",
    labels: ["project-based"],
  },
  {
    id: "node-docs",
    title: "Node.js guides",
    provider: "Node.js",
    url: "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
    type: "documentation",
    level: "beginner",
    durationMinutes: 90,
    language: "en",
    topics: ["node"],
    projectBased: false,
    editorScore: 92,
    lastVerified: V,
    status: "active",
    editorNote: "Official getting-started path.",
    labels: ["official-docs"],
  },
  {
    id: "a11y-mdn",
    title: "MDN Accessibility",
    provider: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Web/Accessibility",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 90,
    language: "en",
    topics: ["accessibility"],
    projectBased: false,
    editorScore: 94,
    lastVerified: V,
    status: "active",
    editorNote: "Learn keyboard, names, and contrast before tooling.",
    labels: ["official-docs"],
  },
  {
    id: "web-dev-a11y",
    title: "Learn Accessibility",
    provider: "web.dev",
    url: "https://web.dev/learn/accessibility/",
    type: "article",
    level: "beginner",
    durationMinutes: 80,
    language: "en",
    topics: ["accessibility"],
    projectBased: false,
    editorScore: 91,
    lastVerified: V,
    status: "active",
    editorNote: "Structured course from Chrome developers.",
    labels: ["best-beginner"],
  },
  {
    id: "owasp-top10",
    title: "OWASP Top 10",
    provider: "OWASP",
    url: "https://owasp.org/www-project-top-ten/",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 90,
    language: "en",
    topics: ["security"],
    projectBased: false,
    editorScore: 96,
    lastVerified: V,
    status: "active",
    editorNote: "Memorize the classes of bugs, then exploit them only in legal labs.",
    labels: ["official-docs"],
  },
  {
    id: "fcc-linux",
    title: "Linux operating system — crash course",
    provider: "freeCodeCamp / Colt Steele",
    url: "https://www.youtube.com/watch?v=ROjZy1WbCIA",
    youtubeId: "ROjZy1WbCIA",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 90,
    language: "en",
    topics: ["linux"],
    projectBased: false,
    editorScore: 87,
    lastVerified: V,
    status: "active",
    editorNote: "Practice every command in a VM or WSL, not only in notes.",
    labels: ["best-beginner"],
  },
  {
    id: "linux-man",
    title: "The Linux command line (online book)",
    provider: "William Shotts",
    url: "https://linuxcommand.org/tlcl.php",
    type: "article",
    level: "beginner",
    durationMinutes: 400,
    language: "en",
    topics: ["linux"],
    projectBased: false,
    editorScore: 93,
    lastVerified: V,
    status: "active",
    editorNote: "Free book. Chapters 1–10 cover daily CLI work.",
    labels: ["hidden-gem"],
  },
  {
    id: "fcc-networking",
    title: "Computer networking — full course",
    provider: "freeCodeCamp / NetworkChuck",
    url: "https://www.youtube.com/watch?v=IPvYjXCsTg8",
    youtubeId: "IPvYjXCsTg8",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 300,
    language: "en",
    topics: ["networking"],
    projectBased: false,
    editorScore: 88,
    lastVerified: V,
    status: "active",
    editorNote: "Draw the OSI/TCP diagrams yourself while watching.",
    labels: ["best-beginner"],
  },
  {
    id: "3b1b-nn",
    title: "Neural networks — Essence of neural networks",
    provider: "3Blue1Brown",
    url: "https://www.youtube.com/watch?v=aircAruvnKk",
    youtubeId: "aircAruvnKk",
    type: "playlist",
    playlistId: "PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
    level: "beginner",
    durationMinutes: 80,
    language: "en",
    topics: ["ml", "neural-networks"],
    projectBased: false,
    editorScore: 99,
    lastVerified: V,
    status: "active",
    editorNote: "Watch the whole playlist. Intuition first, frameworks second.",
    labels: ["best-overall", "best-beginner"],
  },
  {
    id: "fcc-ml",
    title: "Machine learning with Python — full course",
    provider: "freeCodeCamp / freeCodeCamp.org",
    url: "https://www.youtube.com/watch?v=i_LwzRVP7bg",
    youtubeId: "i_LwzRVP7bg",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 360,
    language: "en",
    topics: ["ml", "python"],
    projectBased: true,
    editorScore: 87,
    lastVerified: V,
    status: "active",
    editorNote: "sklearn-oriented. Pair with official User Guide.",
    labels: ["project-based"],
  },
  {
    id: "sklearn-ug",
    title: "scikit-learn user guide",
    provider: "scikit-learn",
    url: "https://scikit-learn.org/stable/user_guide.html",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 240,
    language: "en",
    topics: ["ml"],
    projectBased: false,
    editorScore: 95,
    lastVerified: V,
    status: "active",
    editorNote: "Read Supervised learning + Model selection.",
    labels: ["official-docs"],
  },
  {
    id: "karpathy-gpt",
    title: "Let's build GPT from scratch",
    provider: "Andrej Karpathy",
    url: "https://www.youtube.com/watch?v=kCc8FmEb1nY",
    youtubeId: "kCc8FmEb1nY",
    type: "youtube-course",
    level: "advanced",
    durationMinutes: 120,
    language: "en",
    topics: ["transformers", "python"],
    projectBased: true,
    editorScore: 98,
    lastVerified: V,
    status: "active",
    editorNote: "Type every line. This is the best public transformer lesson we know.",
    labels: ["advanced", "project-based", "best-overall"],
  },
  {
    id: "hf-nlp",
    title: "Hugging Face NLP course",
    provider: "Hugging Face",
    url: "https://huggingface.co/learn/nlp-course",
    type: "interactive",
    level: "intermediate",
    durationMinutes: 480,
    language: "en",
    topics: ["nlp", "transformers"],
    projectBased: true,
    editorScore: 94,
    lastVerified: V,
    status: "active",
    editorNote: "Free. Chapters 1–4 cover the stack you will actually use.",
    labels: ["official-docs", "project-based"],
  },
  {
    id: "openai-prompt",
    title: "Prompt engineering (official)",
    provider: "OpenAI",
    url: "https://platform.openai.com/docs/guides/prompt-engineering",
    type: "documentation",
    level: "beginner",
    durationMinutes: 40,
    language: "en",
    topics: ["prompt-engineering"],
    projectBased: false,
    editorScore: 92,
    lastVerified: V,
    status: "active",
    editorNote: "Vendor docs change; treat patterns as durable, APIs as not.",
    labels: ["official-docs", "fastest"],
  },
  {
    id: "anthropic-prompt",
    title: "Prompt engineering overview",
    provider: "Anthropic",
    url: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview",
    type: "documentation",
    level: "beginner",
    durationMinutes: 45,
    language: "en",
    topics: ["prompt-engineering"],
    projectBased: false,
    editorScore: 91,
    lastVerified: V,
    status: "active",
    editorNote: "Excellent on XML structure and evaluation.",
    labels: ["official-docs"],
  },
  {
    id: "pytorch-tutorials",
    title: "PyTorch tutorials",
    provider: "PyTorch",
    url: "https://pytorch.org/tutorials/beginner/basics/intro.html",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 180,
    language: "en",
    topics: ["pytorch"],
    projectBased: true,
    editorScore: 95,
    lastVerified: V,
    status: "active",
    editorNote: "Official basics track. Run locally or in Colab.",
    labels: ["official-docs"],
  },
  {
    id: "3b1b-linear",
    title: "Essence of linear algebra",
    provider: "3Blue1Brown",
    url: "https://www.youtube.com/watch?v=fNk_zzaMoSs",
    youtubeId: "fNk_zzaMoSs",
    type: "playlist",
    playlistId: "PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
    level: "beginner",
    durationMinutes: 180,
    language: "en",
    topics: ["math"],
    projectBased: false,
    editorScore: 98,
    lastVerified: V,
    status: "active",
    editorNote: "You do not need a full university linear algebra course to start ML — you need this intuition.",
    labels: ["best-beginner"],
  },
  {
    id: "statquest-stats",
    title: "Statistics fundamentals",
    provider: "StatQuest",
    url: "https://www.youtube.com/watch?v=qBigTkBLU6g",
    youtubeId: "qBigTkBLU6g",
    type: "youtube-video",
    level: "beginner",
    durationMinutes: 20,
    language: "en",
    topics: ["stats"],
    projectBased: false,
    editorScore: 90,
    lastVerified: V,
    status: "active",
    editorNote: "Then continue the StatQuest histogram/distribution playlist.",
    labels: ["best-beginner"],
  },
  {
    id: "pandas-docs",
    title: "10 minutes to pandas",
    provider: "pandas",
    url: "https://pandas.pydata.org/docs/user_guide/10min.html",
    type: "documentation",
    level: "beginner",
    durationMinutes: 40,
    language: "en",
    topics: ["python", "data"],
    projectBased: false,
    editorScore: 93,
    lastVerified: V,
    status: "active",
    editorNote: "Type it. Do not only read it.",
    labels: ["official-docs", "fastest"],
  },
  {
    id: "owasp-auth",
    title: "OWASP Authentication Cheat Sheet",
    provider: "OWASP",
    url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html",
    type: "cheatsheet",
    level: "intermediate",
    durationMinutes: 40,
    language: "en",
    topics: ["security", "auth"],
    projectBased: false,
    editorScore: 94,
    lastVerified: V,
    status: "active",
    editorNote: "Required reading before you roll your own auth — which you should not.",
    labels: ["official-docs"],
  },
  {
    id: "vercel-deploy",
    title: "Deploying Next.js on Vercel",
    provider: "Vercel",
    url: "https://nextjs.org/docs/app/building-your-application/deploying",
    type: "documentation",
    level: "beginner",
    durationMinutes: 30,
    language: "en",
    topics: ["deploy"],
    projectBased: true,
    editorScore: 90,
    lastVerified: V,
    status: "active",
    editorNote: "Ship a project publicly. A repo without a URL is unfinished.",
    labels: ["official-docs", "fastest"],
  },
  {
    id: "cryptopals-intro",
    title: "Cryptopals challenges (set 1)",
    provider: "Cryptopals",
    url: "https://cryptopals.com/sets/1",
    type: "project",
    level: "intermediate",
    durationMinutes: 180,
    language: "en",
    topics: ["crypto"],
    projectBased: true,
    editorScore: 92,
    lastVerified: V,
    status: "active",
    editorNote: "Legal, well-designed crypto practice. Do not attack real systems.",
    labels: ["project-based", "hidden-gem"],
  },
  {
    id: "ethics-hacking",
    title: "NIST SP 800-63 digital identity guidelines (overview)",
    provider: "NIST",
    url: "https://pages.nist.gov/800-63-3/",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 60,
    language: "en",
    topics: ["security", "ethics"],
    projectBased: false,
    editorScore: 88,
    lastVerified: V,
    status: "active",
    editorNote: "Grounds identity and access in public standards, not folklore.",
    labels: ["official-docs"],
  },
  {
    id: "cs50p",
    title: "CS50’s Introduction to Programming with Python (lecture 0)",
    provider: "Harvard CS50",
    url: "https://www.youtube.com/watch?v=xLmat4eZ3bY",
    youtubeId: "xLmat4eZ3bY",
    type: "youtube-course",
    level: "beginner",
    durationMinutes: 120,
    language: "en",
    topics: ["python"],
    projectBased: true,
    editorScore: 93,
    lastVerified: V,
    status: "active",
    editorNote: "If you want problem sets with academic rigor, follow the full CS50P course on cs50.harvard.edu.",
    labels: ["project-based"],
  },
  {
    id: "langchain-agents",
    title: "Build an agent (LangChain conceptual docs)",
    provider: "LangChain",
    url: "https://python.langchain.com/docs/tutorials/agents/",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 60,
    language: "en",
    topics: ["agents"],
    projectBased: true,
    editorScore: 82,
    lastVerified: V,
    status: "active",
    editorNote: "Libraries churn. Learn the ideas (tools, memory, control loop), not the import paths.",
    labels: ["project-based"],
  },
  {
    id: "openai-agents",
    title: "Function calling / tools (OpenAI)",
    provider: "OpenAI",
    url: "https://platform.openai.com/docs/guides/function-calling",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 40,
    language: "en",
    topics: ["agents", "tools"],
    projectBased: false,
    editorScore: 90,
    lastVerified: V,
    status: "active",
    editorNote: "The primitive behind most ‘agents’.",
    labels: ["official-docs"],
  },
  {
    id: "owasp-llm",
    title: "OWASP Top 10 for LLM Applications",
    provider: "OWASP",
    url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 50,
    language: "en",
    topics: ["ai-safety", "security"],
    projectBased: false,
    editorScore: 91,
    lastVerified: V,
    status: "active",
    editorNote: "Prompt injection is a security bug, not a vibe.",
    labels: ["official-docs", "advanced"],
  },
  {
    id: "hf-agents",
    title: "Hugging Face agents course",
    provider: "Hugging Face",
    url: "https://huggingface.co/learn/agents-course",
    type: "interactive",
    level: "intermediate",
    durationMinutes: 360,
    language: "en",
    topics: ["agents"],
    projectBased: true,
    editorScore: 88,
    lastVerified: V,
    status: "active",
    editorNote: "Free structured path. Prefer building a tiny agent over collecting frameworks.",
    labels: ["project-based"],
  },
  {
    id: "kaggle-intro-ml",
    title: "Intro to Machine Learning",
    provider: "Kaggle",
    url: "https://www.kaggle.com/learn/intro-to-machine-learning",
    type: "interactive",
    level: "beginner",
    durationMinutes: 180,
    language: "en",
    topics: ["ml"],
    projectBased: true,
    editorScore: 89,
    lastVerified: V,
    status: "active",
    editorNote: "Short, free, in-browser notebooks.",
    labels: ["fastest", "best-beginner"],
  },
  {
    id: "mlops-google",
    title: "MLOps: Continuous delivery and automation practices",
    provider: "Google Cloud",
    url: "https://cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning",
    type: "article",
    level: "advanced",
    durationMinutes: 45,
    language: "en",
    topics: ["mlops"],
    projectBased: false,
    editorScore: 90,
    lastVerified: V,
    status: "active",
    editorNote: "Read for the levels of automation, not the GCP product names.",
    labels: ["advanced"],
  },
  {
    id: "testing-library",
    title: "Testing Library docs",
    provider: "Testing Library",
    url: "https://testing-library.com/docs/",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 40,
    language: "en",
    topics: ["testing", "javascript"],
    projectBased: false,
    editorScore: 91,
    lastVerified: V,
    status: "active",
    editorNote: "Test behaviour, not implementation details.",
    labels: ["official-docs"],
  },
  {
    id: "drizzle-docs",
    title: "Drizzle ORM — Get Started",
    provider: "Drizzle",
    url: "https://orm.drizzle.team/docs/get-started/sqlite-new",
    type: "documentation",
    level: "intermediate",
    durationMinutes: 40,
    language: "en",
    topics: ["sql", "orm"],
    projectBased: true,
    editorScore: 88,
    lastVerified: V,
    status: "active",
    editorNote: "Lightweight ORM used by LearnPath itself.",
    labels: ["official-docs"],
  },
  {
    id: "portswigger-xss",
    title: "PortSwigger Web Security Academy — XSS",
    provider: "PortSwigger",
    url: "https://portswigger.net/web-security/cross-site-scripting",
    type: "interactive",
    level: "intermediate",
    durationMinutes: 120,
    language: "en",
    topics: ["security"],
    projectBased: true,
    editorScore: 96,
    lastVerified: V,
    review: { clarity: 5, handsOn: 5, freshness: 5, projects: 4, beginner: 3 },
    status: "active",
    editorNote: "Legal labs. Never test systems you do not own or have written permission to test.",
    labels: ["project-based", "best-overall"],
  },
];
