import type { Roadmap } from "./schema";

type Node = Roadmap["nodes"][number];

function line(
  ids: { id: string; skillId: string; tier: Node["tier"]; requirement?: Node["requirement"] }[],
  startX = 80,
  startY = 80,
  dx = 0,
  dy = 90,
) {
  return ids.map((n, i) => ({
    ...n,
    requirement: n.requirement ?? "required",
    x: startX + dx * i + (i % 2 === 1 ? 40 : 0),
    y: startY + dy * i,
  }));
}

function chain(ids: string[]): Roadmap["edges"] {
  return ids.slice(1).map((to, i) => ({ from: ids[i], to, kind: "required" as const }));
}

export const roadmaps = [
  {
    id: "python-developer",
    slug: "python-developer",
    title: "Python Developer",
    tagline: "From zero to fluent — syntax, structure, tests, and a real CLI.",
    description:
      "A tightly scoped path for people who want to write Python they can trust. You will set up a real environment, learn the language (not a framework zoo), test your code, and ship a command-line project.",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 80,
    featured: true,
    editorPick: true,
    color: "#2DD4BF",
    prerequisites: [],
    nodes: line([
      { id: "n-setup", skillId: "python-setup", tier: "foundation" },
      { id: "n-syntax", skillId: "python-syntax", tier: "foundation" },
      { id: "n-fn", skillId: "python-functions", tier: "core" },
      { id: "n-ds", skillId: "python-data-structures", tier: "core" },
      { id: "n-err", skillId: "python-errors", tier: "core" },
      { id: "n-oop", skillId: "python-oop", tier: "core" },
      { id: "n-files", skillId: "python-files", tier: "practice" },
      { id: "n-test", skillId: "python-testing", tier: "practice" },
      { id: "n-git", skillId: "git-basics", tier: "practice" },
      { id: "n-sql", skillId: "sql-fundamentals", tier: "project", requirement: "recommended" },
    ]),
    edges: chain(["n-setup", "n-syntax", "n-fn", "n-ds", "n-err", "n-oop", "n-files", "n-test", "n-git", "n-sql"]),
  },
  {
    id: "full-stack-developer",
    slug: "full-stack-developer",
    title: "Full Stack Developer",
    tagline: "HTML to a deployed app — frontend, API, data, and auth.",
    description:
      "A project-oriented web path. You learn HTML/CSS and JavaScript deeply, add TypeScript, React, a Node API, SQL, authentication, tests, and a public deploy. Quality over framework fashion.",
    category: "web",
    difficulty: "beginner",
    estimatedHours: 160,
    featured: true,
    editorPick: true,
    color: "#7AA2FF",
    prerequisites: [],
    nodes: line([
      { id: "n-html", skillId: "html-css", tier: "foundation" },
      { id: "n-js", skillId: "javascript-fundamentals", tier: "foundation" },
      { id: "n-git", skillId: "git-basics", tier: "foundation" },
      { id: "n-a11y", skillId: "accessibility", tier: "core" },
      { id: "n-ts", skillId: "typescript-fundamentals", tier: "core" },
      { id: "n-react", skillId: "react-fundamentals", tier: "core" },
      { id: "n-node", skillId: "node-express", tier: "core" },
      { id: "n-sql", skillId: "sql-fundamentals", tier: "practice" },
      { id: "n-orm", skillId: "databases-orm", tier: "practice" },
      { id: "n-auth", skillId: "web-auth", tier: "practice" },
      { id: "n-test", skillId: "web-testing", tier: "project" },
      { id: "n-deploy", skillId: "deploy-basics", tier: "mastery" },
    ]),
    edges: chain([
      "n-html",
      "n-js",
      "n-git",
      "n-a11y",
      "n-ts",
      "n-react",
      "n-node",
      "n-sql",
      "n-orm",
      "n-auth",
      "n-test",
      "n-deploy",
    ]),
  },
  {
    id: "ai-engineer",
    slug: "ai-engineer",
    title: "AI Engineer",
    tagline: "Math intuition, data, classical ML, networks, and responsible shipping.",
    description:
      "For builders who want to understand models, not only call APIs. Python, data wrangling, classical ML, neural nets, evaluation, and a sober look at ethics and operations.",
    category: "ai",
    difficulty: "intermediate",
    estimatedHours: 180,
    featured: true,
    editorPick: true,
    color: "#F5B942",
    prerequisites: [],
    nodes: line([
      { id: "n-py", skillId: "python-syntax", tier: "foundation" },
      { id: "n-ds", skillId: "python-data-structures", tier: "foundation" },
      { id: "n-lin", skillId: "linear-algebra-intuition", tier: "foundation" },
      { id: "n-stat", skillId: "probability-stats", tier: "foundation" },
      { id: "n-sql", skillId: "sql-fundamentals", tier: "core" },
      { id: "n-wrangle", skillId: "data-wrangling", tier: "core" },
      { id: "n-ml", skillId: "ml-fundamentals", tier: "core" },
      { id: "n-nn", skillId: "neural-networks", tier: "core" },
      { id: "n-torch", skillId: "pytorch-intro", tier: "practice" },
      { id: "n-eval", skillId: "model-evaluation", tier: "practice" },
      { id: "n-ops", skillId: "mlops-basics", tier: "project" },
      { id: "n-eth", skillId: "ai-ethics", tier: "mastery" },
    ]),
    edges: [
      ...chain(["n-py", "n-ds", "n-wrangle", "n-ml", "n-nn", "n-torch", "n-eval", "n-ops", "n-eth"]),
      { from: "n-lin", to: "n-nn", kind: "required" },
      { from: "n-stat", to: "n-ml", kind: "required" },
      { from: "n-sql", to: "n-wrangle", kind: "recommended" },
    ],
  },
  {
    id: "generative-ai-engineer",
    slug: "generative-ai-engineer",
    title: "Generative AI Engineer",
    tagline: "Transformers, prompting, RAG, evals — build with language models on purpose.",
    description:
      "A path for people who will ship LLM features. You learn enough of the stack to debug token limits, retrieval failures, and unsafe outputs — not only to paste prompts.",
    category: "ai",
    difficulty: "intermediate",
    estimatedHours: 120,
    featured: true,
    color: "#C084FC",
    prerequisites: ["python-developer"],
    nodes: line([
      { id: "n-py", skillId: "python-syntax", tier: "foundation" },
      { id: "n-nn", skillId: "neural-networks", tier: "foundation" },
      { id: "n-tx", skillId: "transformers-llms", tier: "core" },
      { id: "n-prompt", skillId: "prompt-engineering", tier: "core" },
      { id: "n-rag", skillId: "embeddings-rag", tier: "core" },
      { id: "n-ft", skillId: "fine-tuning-basics", tier: "practice", requirement: "optional" },
      { id: "n-eval", skillId: "genai-eval-safety", tier: "project" },
      { id: "n-eth", skillId: "ai-ethics", tier: "mastery" },
    ]),
    edges: chain(["n-py", "n-nn", "n-tx", "n-prompt", "n-rag", "n-ft", "n-eval", "n-eth"]),
  },
  {
    id: "agentic-ai-engineer",
    slug: "agentic-ai-engineer",
    title: "Agentic AI Engineer",
    tagline: "Tools, loops, memory, and safety — agents you can actually debug.",
    description:
      "Agents are programs that call tools in a loop. This path treats them as software: schemas, logs, step limits, and least privilege. Multi-agent theatre is optional; reliability is not.",
    category: "ai",
    difficulty: "advanced",
    estimatedHours: 100,
    featured: true,
    color: "#FB7185",
    prerequisites: ["generative-ai-engineer"],
    nodes: line([
      { id: "n-py", skillId: "python-functions", tier: "foundation" },
      { id: "n-prompt", skillId: "prompt-engineering", tier: "foundation" },
      { id: "n-tools", skillId: "tool-use-apis", tier: "core" },
      { id: "n-arch", skillId: "agent-architecture", tier: "core" },
      { id: "n-mem", skillId: "memory-planning", tier: "practice" },
      { id: "n-multi", skillId: "multi-agent", tier: "practice", requirement: "optional" },
      { id: "n-safe", skillId: "agent-safety", tier: "mastery" },
      { id: "n-owasp", skillId: "ai-ethics", tier: "mastery" },
    ]),
    edges: chain(["n-py", "n-prompt", "n-tools", "n-arch", "n-mem", "n-multi", "n-safe", "n-owasp"]),
  },
  {
    id: "junior-cybersecurity",
    slug: "junior-cybersecurity",
    title: "Junior Cybersecurity Professional",
    tagline: "Ethical foundations, Linux, networks, web bugs, and incident basics.",
    description:
      "A junior defensive-leaning path. You will learn the command line, how networks work, how web apps fail (in legal labs only), cryptography hygiene, and how to behave under an incident. Unauthorized access is out of scope — forever.",
    category: "security",
    difficulty: "beginner",
    estimatedHours: 140,
    featured: true,
    editorPick: true,
    color: "#34D399",
    prerequisites: [],
    nodes: line([
      { id: "n-eth", skillId: "ethics-law", tier: "foundation" },
      { id: "n-linux", skillId: "linux-cli", tier: "foundation" },
      { id: "n-net", skillId: "networking-basics", tier: "foundation" },
      { id: "n-py", skillId: "python-syntax", tier: "core" },
      { id: "n-git", skillId: "git-basics", tier: "core" },
      { id: "n-owasp", skillId: "owasp-web", tier: "core" },
      { id: "n-crypto", skillId: "cryptography-basics", tier: "practice" },
      { id: "n-recon", skillId: "recon-osint", tier: "practice" },
      { id: "n-vuln", skillId: "vuln-assessment", tier: "project" },
      { id: "n-hard", skillId: "linux-hardening", tier: "project" },
      { id: "n-ir", skillId: "incident-response", tier: "mastery" },
    ]),
    edges: [
      ...chain(["n-eth", "n-linux", "n-net", "n-py", "n-git", "n-owasp", "n-crypto", "n-recon", "n-vuln", "n-hard", "n-ir"]),
    ],
  },
];
