export const skills = [
  {
    id: "python-setup",
    slug: "python-setup",
    title: "Python setup & tooling",
    summary: "Install Python 3, run files, use a virtual environment, and know where pip packages live.",
    objectives: [
      "Run python3 --version and a hello script",
      "Create and activate a virtual environment",
      "Install a package with pip and freeze requirements",
    ],
    prerequisites: [],
    resources: { best: "fcc-python-4h", alternative: "cs50p", docs: "python-docs", quick: "python-docs" },
    practiceId: "python-hello",
    challengeIds: ["py-hello"],
  },
  {
    id: "python-syntax",
    slug: "python-syntax",
    title: "Python syntax & types",
    summary: "Names, types, control flow, and the difference between expressions and statements.",
    objectives: [
      "Use ints, floats, strings, bools, and None",
      "Write if/elif/else and for/while loops",
      "Format strings and convert types without losing data",
    ],
    prerequisites: ["python-setup"],
    resources: { best: "fcc-python", alternative: "fcc-python-4h", docs: "python-docs", quick: "fcc-python-4h" },
    practiceId: "python-syntax",
    challengeIds: ["py-fizzbuzz"],
  },
  {
    id: "python-functions",
    slug: "python-functions",
    title: "Functions & scope",
    summary: "Define reusable functions, pass arguments, return values, and reason about scope.",
    objectives: [
      "Write functions with positional and keyword arguments",
      "Return values instead of printing when composing programs",
      "Explain local vs global names",
    ],
    prerequisites: ["python-syntax"],
    resources: { best: "fcc-python", docs: "python-docs", alternative: "cs50p" },
    practiceId: "python-functions",
    challengeIds: ["py-palindrome"],
  },
  {
    id: "python-data-structures",
    slug: "python-data-structures",
    title: "Lists, dicts, sets",
    summary: "Choose the right built-in collection and use comprehensions without making them unreadable.",
    objectives: [
      "Index, slice, and mutate lists",
      "Look up and update dictionaries",
      "Know when a set is the right tool",
    ],
    prerequisites: ["python-functions"],
    resources: { best: "fcc-python", docs: "python-docs" },
    practiceId: "python-collections",
    challengeIds: ["py-wordcount"],
  },
  {
    id: "python-oop",
    slug: "python-oop",
    title: "Objects & classes",
    summary: "Model state with classes. Prefer composition. Know dunder methods you will actually use.",
    objectives: [
      "Define a class with __init__ and methods",
      "Use inheritance only when it is a real is-a relationship",
      "Implement __repr__ for debugging",
    ],
    prerequisites: ["python-data-structures"],
    resources: { best: "realpython-oop", docs: "python-docs", alternative: "fcc-python" },
    practiceId: "python-oop",
    challengeIds: ["py-counter-class"],
    projectIds: ["py-cli-todo"],
  },
  {
    id: "python-errors",
    slug: "python-errors",
    title: "Errors & debugging",
    summary: "Read tracebacks, raise exceptions, and handle only the errors you can recover from.",
    objectives: [
      "Read a traceback from the bottom up",
      "Use try/except/else/finally appropriately",
      "Raise ValueError with a useful message",
    ],
    prerequisites: ["python-functions"],
    resources: { best: "python-docs", alternative: "fcc-python" },
    practiceId: "python-errors",
    challengeIds: ["py-safe-divide"],
  },
  {
    id: "python-testing",
    slug: "python-testing",
    title: "Testing with pytest",
    summary: "If it is not tested, it is a demo. Write assertions that document behaviour.",
    objectives: [
      "Write a pytest function that fails then passes",
      "Parametrize a test",
      "Treat tests as the spec for a function",
    ],
    prerequisites: ["python-functions"],
    resources: { best: "pytest-docs", docs: "pytest-docs" },
    practiceId: "python-functions",
    challengeIds: ["py-palindrome"],
  },
  {
    id: "python-files",
    slug: "python-files",
    title: "Files & text",
    summary: "Read and write text files with context managers. Handle encodings on purpose.",
    objectives: [
      "Use with open(...) as f",
      "Read line by line vs all at once",
      "Write UTF-8 text",
    ],
    prerequisites: ["python-syntax"],
    resources: { best: "fcc-python", docs: "python-docs" },
    practiceId: "python-files",
    challengeIds: ["py-wordcount"],
    projectIds: ["py-cli-todo"],
  },
  {
    id: "git-basics",
    slug: "git-basics",
    title: "Git & GitHub",
    summary: "Snapshot work, branch, review diffs, and collaborate without rewriting shared history casually.",
    objectives: [
      "init, add, commit, log, status, diff",
      "Create a branch and open a pull request",
      "Write commit messages that explain why",
    ],
    prerequisites: [],
    resources: { best: "fcc-git", docs: "pro-git", alternative: "pro-git" },
  },
  {
    id: "sql-fundamentals",
    slug: "sql-fundamentals",
    title: "SQL fundamentals",
    summary: "Query relational data with SELECT, WHERE, JOIN, GROUP BY. Think in sets.",
    objectives: [
      "Filter and project rows",
      "JOIN two tables on a key",
      "Aggregate with GROUP BY and HAVING",
    ],
    prerequisites: [],
    resources: { best: "fcc-sql", docs: "sqlite-docs", quick: "sqlite-docs" },
    practiceId: "sql-select",
    challengeIds: ["sql-books"],
    projectIds: ["sql-library"],
  },
  {
    id: "html-css",
    slug: "html-css",
    title: "HTML & CSS",
    summary: "Semantic documents and layouts you can read in the DOM, not a pile of divs.",
    objectives: [
      "Use headings, lists, forms, and landmarks correctly",
      "Layout with flexbox and grid",
      "Ship readable typography and spacing",
    ],
    prerequisites: [],
    resources: { best: "fcc-html-css", docs: "mdn-html", alternative: "mdn-html" },
    practiceId: "html-card",
    challengeIds: ["html-profile"],
    projectIds: ["web-portfolio"],
  },
  {
    id: "javascript-fundamentals",
    slug: "javascript-fundamentals",
    title: "JavaScript fundamentals",
    summary: "Language of the web: values, functions, arrays, objects, and asynchrony.",
    objectives: [
      "Use let/const, functions, and array methods",
      "Understand equality, truthiness, and this enough to not be surprised",
      "Fetch JSON and handle errors",
    ],
    prerequisites: ["html-css"],
    resources: { best: "javascript-info", alternative: "fcc-javascript", docs: "mdn-js" },
    extraResourceIds: ["fcc-javascript"],
    practiceId: "js-arrays",
    challengeIds: ["js-unique", "js-fizzbuzz"],
  },
  {
    id: "typescript-fundamentals",
    slug: "typescript-fundamentals",
    title: "TypeScript fundamentals",
    summary: "Make illegal states unrepresentable. Types are a design tool, not decoration.",
    objectives: [
      "Annotate functions and objects",
      "Use unions and narrowing",
      "Read compiler errors instead of fighting them with any",
    ],
    prerequisites: ["javascript-fundamentals"],
    resources: { best: "ts-handbook", alternative: "fcc-typescript", docs: "ts-handbook" },
    practiceId: "ts-types",
    challengeIds: ["ts-narrow"],
  },
  {
    id: "accessibility",
    slug: "accessibility",
    title: "Web accessibility",
    summary: "If it only works with a mouse and perfect vision, it is unfinished.",
    objectives: [
      "Navigate a page with only a keyboard",
      "Name buttons and inputs for assistive tech",
      "Meet contrast and text-resize basics",
    ],
    prerequisites: ["html-css"],
    resources: { best: "web-dev-a11y", docs: "a11y-mdn" },
    practiceId: "html-card",
    projectIds: ["web-portfolio"],
  },
  {
    id: "react-fundamentals",
    slug: "react-fundamentals",
    title: "React fundamentals",
    summary: "UI as a function of state. Components, hooks, and data flow.",
    objectives: [
      "Build components with props and useState",
      "Lift state and pass callbacks",
      "Fetch data with useEffect without infinite loops",
    ],
    prerequisites: ["javascript-fundamentals"],
    resources: { best: "react-docs", alternative: "fcc-react", docs: "react-docs" },
    practiceId: "js-arrays",
    projectIds: ["web-portfolio"],
  },
  {
    id: "node-express",
    slug: "node-express",
    title: "Node.js & HTTP APIs",
    summary: "Serve JSON over HTTP. Validate input. Never trust the client.",
    objectives: [
      "Create an Express (or similar) server",
      "Implement GET/POST with JSON bodies",
      "Return correct status codes",
    ],
    prerequisites: ["javascript-fundamentals"],
    resources: { best: "fcc-node", docs: "node-docs" },
    practiceId: "js-arrays",
    projectIds: ["js-notes-api"],
  },
  {
    id: "databases-orm",
    slug: "databases-orm",
    title: "Databases & ORMs",
    summary: "Persist data with SQL. An ORM is a tool, not a substitute for understanding queries.",
    objectives: [
      "Model tables and foreign keys",
      "Run a migration",
      "Write a query you could also write in SQL",
    ],
    prerequisites: ["sql-fundamentals"],
    resources: { best: "drizzle-docs", docs: "sqlite-docs", alternative: "fcc-sql" },
    practiceId: "sql-joins",
    challengeIds: ["sql-books"],
  },
  {
    id: "web-auth",
    slug: "web-auth",
    title: "Authentication for the web",
    summary: "Sessions, cookies, OAuth. Know what you are trusting.",
    objectives: [
      "Explain why passwords are hashed",
      "Describe an OAuth authorization code flow",
      "List what belongs in an HTTP-only cookie",
    ],
    prerequisites: ["node-express"],
    resources: { best: "owasp-auth", docs: "owasp-auth" },
  },
  {
    id: "web-testing",
    slug: "web-testing",
    title: "Testing web apps",
    summary: "Unit the pure logic. Test the UI the way a user uses it.",
    objectives: [
      "Write a function test without a browser",
      "Query the DOM by role/name",
      "Avoid testing implementation details",
    ],
    prerequisites: ["javascript-fundamentals"],
    resources: { best: "testing-library", docs: "testing-library" },
    challengeIds: ["js-unique"],
  },
  {
    id: "deploy-basics",
    slug: "deploy-basics",
    title: "Deploy & ship",
    summary: "A project is not done until someone else can open the URL.",
    objectives: [
      "Deploy a frontend to a host",
      "Set environment variables without committing secrets",
      "Check the production build locally first",
    ],
    prerequisites: ["git-basics"],
    resources: { best: "vercel-deploy", docs: "vercel-deploy" },
    projectIds: ["web-portfolio"],
  },
  {
    id: "linear-algebra-intuition",
    slug: "linear-algebra-intuition",
    title: "Linear algebra intuition",
    summary: "Vectors, matrices, and linear maps as geometry — enough to read ML papers without panic.",
    objectives: [
      "Explain a vector as a list and as an arrow",
      "Multiply a matrix and a vector by hand for 2D",
      "Connect dot products to similarity",
    ],
    prerequisites: [],
    resources: { best: "3b1b-linear", docs: "3b1b-linear" },
  },
  {
    id: "probability-stats",
    slug: "probability-stats",
    title: "Probability & statistics",
    summary: "Distributions, expectation, and why test sets exist.",
    objectives: [
      "Read a histogram",
      "Explain mean vs median",
      "Describe train/test split as an experiment",
    ],
    prerequisites: [],
    resources: { best: "statquest-stats", alternative: "kaggle-intro-ml" },
  },
  {
    id: "data-wrangling",
    slug: "data-wrangling",
    title: "Data wrangling",
    summary: "Most of applied ML is cleaning tables. Get comfortable with pandas.",
    objectives: [
      "Load a CSV and inspect dtypes",
      "Filter, group, and join frames",
      "Handle missing values on purpose",
    ],
    prerequisites: ["python-data-structures"],
    resources: { best: "pandas-docs", docs: "pandas-docs" },
    practiceId: "python-collections",
  },
  {
    id: "ml-fundamentals",
    slug: "ml-fundamentals",
    title: "Machine learning fundamentals",
    summary: "Supervised learning, features, loss, overfitting. Models are not magic.",
    objectives: [
      "Fit a baseline model",
      "Evaluate with an appropriate metric",
      "Diagnose overfitting vs underfitting",
    ],
    prerequisites: ["python-syntax", "probability-stats"],
    resources: { best: "kaggle-intro-ml", alternative: "fcc-ml", docs: "sklearn-ug" },
  },
  {
    id: "neural-networks",
    slug: "neural-networks",
    title: "Neural networks",
    summary: "Layers, activations, backprop as computational graph. Intuition before frameworks.",
    objectives: [
      "Draw a 2-layer network",
      "Explain what a loss is optimizing",
      "Relate gradient descent to walking downhill",
    ],
    prerequisites: ["linear-algebra-intuition", "ml-fundamentals"],
    resources: { best: "3b1b-nn", alternative: "fcc-ml" },
  },
  {
    id: "pytorch-intro",
    slug: "pytorch-intro",
    title: "PyTorch basics",
    summary: "Tensors, autograd, a training loop you could rewrite from memory.",
    objectives: [
      "Create tensors and run a forward pass",
      "Write a training loop with loss.backward() and optimizer.step()",
      "Move a model to GPU when available",
    ],
    prerequisites: ["neural-networks", "python-functions"],
    resources: { best: "pytorch-tutorials", docs: "pytorch-tutorials" },
  },
  {
    id: "model-evaluation",
    slug: "model-evaluation",
    title: "Evaluation & metrics",
    summary: "Accuracy lies. Choose metrics that match the decision.",
    objectives: [
      "Explain precision vs recall",
      "Use a confusion matrix",
      "Hold out data that the model never trained on",
    ],
    prerequisites: ["ml-fundamentals"],
    resources: { best: "sklearn-ug", docs: "sklearn-ug" },
  },
  {
    id: "mlops-basics",
    slug: "mlops-basics",
    title: "MLOps basics",
    summary: "Version data and models. A notebook is not a production system.",
    objectives: [
      "Describe the difference between experiment and production",
      "Name what you would log for a training run",
      "Sketch a simple training → eval → deploy pipeline",
    ],
    prerequisites: ["ml-fundamentals"],
    resources: { best: "mlops-google", docs: "mlops-google" },
  },
  {
    id: "ai-ethics",
    slug: "ai-ethics",
    title: "AI ethics & responsibility",
    summary: "Datasets encode history. Models amplify it. You are accountable for what you ship.",
    objectives: [
      "List failure modes: bias, privacy, dual use",
      "Ask who is harmed if the model is wrong",
      "Refuse to train on data you have no right to use",
    ],
    prerequisites: [],
    resources: { best: "owasp-llm", docs: "owasp-llm" },
  },
  {
    id: "transformers-llms",
    slug: "transformers-llms",
    title: "Transformers & LLMs",
    summary: "Attention, tokens, and why next-token prediction scales.",
    objectives: [
      "Explain self-attention in one paragraph",
      "Tokenize a sentence and estimate context length",
      "Train a tiny GPT on a toy corpus (Karpathy)",
    ],
    prerequisites: ["neural-networks"],
    resources: { best: "karpathy-gpt", alternative: "hf-nlp", docs: "hf-nlp" },
    projectIds: ["py-mini-tokenizer"],
  },
  {
    id: "prompt-engineering",
    slug: "prompt-engineering",
    title: "Prompting & specification",
    summary: "Prompts are programs in English. Be specific, show examples, evaluate.",
    objectives: [
      "Write a prompt with role, constraints, and output schema",
      "Use few-shot examples",
      "Measure quality with a tiny eval set, not vibes",
    ],
    prerequisites: [],
    resources: { best: "openai-prompt", alternative: "anthropic-prompt", docs: "openai-prompt" },
  },
  {
    id: "embeddings-rag",
    slug: "embeddings-rag",
    title: "Embeddings & RAG",
    summary: "Retrieve then generate. Garbage retrieval is garbage generation.",
    objectives: [
      "Explain cosine similarity of embeddings",
      "Chunk documents on purpose",
      "Cite retrieved context in the answer",
    ],
    prerequisites: ["prompt-engineering"],
    resources: { best: "hf-nlp", docs: "hf-nlp" },
  },
  {
    id: "fine-tuning-basics",
    slug: "fine-tuning-basics",
    title: "Fine-tuning basics",
    summary: "When prompting is not enough. Data quality beats parameter count.",
    objectives: [
      "Decide when not to fine-tune",
      "Format instruction data",
      "Evaluate against a frozen baseline",
    ],
    prerequisites: ["transformers-llms"],
    resources: { best: "hf-nlp", docs: "pytorch-tutorials" },
  },
  {
    id: "genai-eval-safety",
    slug: "genai-eval-safety",
    title: "GenAI evaluation & safety",
    summary: "Hallucinations, jailbreaks, and eval harnesses. If you cannot measure it, you cannot improve it.",
    objectives: [
      "Build a 20-example eval set",
      "Name prompt injection as a security issue",
      "Refuse disallowed tasks in the system spec",
    ],
    prerequisites: ["prompt-engineering"],
    resources: { best: "owasp-llm", docs: "owasp-llm" },
  },
  {
    id: "tool-use-apis",
    slug: "tool-use-apis",
    title: "Tools & function calling",
    summary: "LLMs that can call functions. Schema, validation, and least privilege.",
    objectives: [
      "Define a JSON schema for a tool",
      "Validate arguments before executing",
      "Keep tools sandboxed and scoped",
    ],
    prerequisites: ["prompt-engineering", "python-functions"],
    resources: { best: "openai-agents", alternative: "langchain-agents", docs: "openai-agents" },
    practiceId: "python-functions",
    projectIds: ["py-tool-agent"],
  },
  {
    id: "agent-architecture",
    slug: "agent-architecture",
    title: "Agent architecture",
    summary: "A loop: observe, think, act, observe. Keep it small enough to debug.",
    objectives: [
      "Implement a tool-using loop in <150 lines",
      "Log every tool call",
      "Stop on max steps",
    ],
    prerequisites: ["tool-use-apis"],
    resources: { best: "hf-agents", alternative: "langchain-agents" },
    projectIds: ["py-tool-agent"],
  },
  {
    id: "memory-planning",
    slug: "memory-planning",
    title: "Memory & planning",
    summary: "Short-term context vs long-term store. Plans that can be revised.",
    objectives: [
      "Separate working memory from retrieved memory",
      "Write a plan then execute step by step",
      "Know when memory poisons the next step",
    ],
    prerequisites: ["agent-architecture"],
    resources: { best: "hf-agents", docs: "langchain-agents" },
  },
  {
    id: "multi-agent",
    slug: "multi-agent",
    title: "Multi-agent patterns",
    summary: "More agents is not more intelligence. Interfaces and ownership matter.",
    objectives: [
      "Split researcher vs executor roles",
      "Define a shared artifact, not a telepathic bus",
      "Debug by reading transcripts",
    ],
    prerequisites: ["agent-architecture"],
    resources: { best: "hf-agents", docs: "hf-agents" },
  },
  {
    id: "agent-safety",
    slug: "agent-safety",
    title: "Agent safety",
    summary: "Agents take actions. Treat them like untrusted users of your systems.",
    objectives: [
      "Deny network or filesystem by default",
      "Human-in-the-loop for irreversible actions",
      "Assume prompt injection from any retrieved text",
    ],
    prerequisites: ["agent-architecture"],
    resources: { best: "owasp-llm", docs: "owasp-llm" },
  },
  {
    id: "linux-cli",
    slug: "linux-cli",
    title: "Linux command line",
    summary: "The shell is a programming environment. Files, processes, permissions.",
    objectives: [
      "Navigate, inspect, and search the filesystem",
      "Read permissions and processes",
      "Pipe commands instead of writing one-off scripts too early",
    ],
    prerequisites: [],
    resources: { best: "fcc-linux", alternative: "linux-man", docs: "linux-man" },
  },
  {
    id: "networking-basics",
    slug: "networking-basics",
    title: "Networking basics",
    summary: "Packets, ports, DNS, TLS. You cannot secure what you cannot picture.",
    objectives: [
      "Explain IP, TCP, UDP, DNS",
      "Read a URL into scheme/host/path",
      "Describe what a TLS handshake buys you",
    ],
    prerequisites: [],
    resources: { best: "fcc-networking", docs: "fcc-networking" },
  },
  {
    id: "owasp-web",
    slug: "owasp-web",
    title: "Web vulnerabilities (OWASP)",
    summary: "XSS, SQLi, CSRF, SSRF — as classes of bugs, practiced only in legal labs.",
    objectives: [
      "Explain XSS vs SQLi in one sentence each",
      "Use PortSwigger labs, never random websites",
      "Fix the bug in your own code after exploiting the lab",
    ],
    prerequisites: ["html-css", "sql-fundamentals"],
    resources: { best: "portswigger-xss", alternative: "owasp-top10", docs: "owasp-top10" },
  },
  {
    id: "cryptography-basics",
    slug: "cryptography-basics",
    title: "Cryptography basics",
    summary: "Hashing, symmetric vs public key, why you do not invent ciphers.",
    objectives: [
      "Contrast hashing, encryption, and encoding",
      "Use a standard library, never homemade crypto",
      "Solve Cryptopals set 1 challenges 1–3",
    ],
    prerequisites: ["python-syntax"],
    resources: { best: "cryptopals-intro", docs: "cryptopals-intro" },
    practiceId: "python-syntax",
  },
  {
    id: "recon-osint",
    slug: "recon-osint",
    title: "Recon & OSINT (ethical)",
    summary: "Public information gathering with consent and law. Scope is everything.",
    objectives: [
      "Define rules of engagement before any recon",
      "Use only public sources on in-scope assets",
      "Document findings without storing unrelated personal data",
    ],
    prerequisites: ["networking-basics", "ethics-law"],
    resources: { best: "owasp-top10", docs: "ethics-hacking" },
  },
  {
    id: "vuln-assessment",
    slug: "vuln-assessment",
    title: "Vulnerability assessment",
    summary: "Find, rank, and report issues. A scanner without a brain is noise.",
    objectives: [
      "Reproduce a finding manually",
      "Score impact vs likelihood",
      "Write a report a developer can act on",
    ],
    prerequisites: ["owasp-web"],
    resources: { best: "portswigger-xss", docs: "owasp-top10" },
  },
  {
    id: "linux-hardening",
    slug: "linux-hardening",
    title: "Linux hardening",
    summary: "Least privilege, updates, SSH, firewalls. Defense in boring layers.",
    objectives: [
      "Disable password SSH in a lab VM",
      "Explain why root login is a bad default",
      "List what you would log",
    ],
    prerequisites: ["linux-cli"],
    resources: { best: "linux-man", docs: "linux-man" },
  },
  {
    id: "incident-response",
    slug: "incident-response",
    title: "Incident response basics",
    summary: "Prepare, detect, contain, recover, learn. Panic is not a process.",
    objectives: [
      "Write a one-page IR checklist",
      "Preserve evidence before ‘fixing’",
      "Communicate clearly during an incident",
    ],
    prerequisites: ["linux-cli", "networking-basics"],
    resources: { best: "ethics-hacking", docs: "ethics-hacking" },
  },
  {
    id: "ethics-law",
    slug: "ethics-law",
    title: "Ethics, law & scope",
    summary: "Unauthorized access is a crime. Curiosity is not consent.",
    objectives: [
      "State that you will only test systems you own or have written permission to test",
      "Recognize that ‘but it was open’ is not a defense",
      "Handle data you encounter as if it were your own",
    ],
    prerequisites: [],
    resources: { best: "ethics-hacking", docs: "ethics-hacking" },
  },
];
